# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketrequest',
            name='department',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='ticketrequest',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.TypeRequest'),
        ),
    ]
