# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20170929_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketrequest',
            name='department',
        ),
    ]
